disabled_rules:
  - line_length
  - todo
  - type_name
  - identifier_name
  - force_try
  - file_length
  - function_parameter_count
  - redundant_string_enum_value
  - unneeded_synthesized_initializer
  - multiple_closures_with_trailing_closure
  - trailing_comma
  - opening_brace
  - closure_parameter_position
  - optional_data_string_conversion

# ========================================
# Complexity Thresholds (Task A7)
# ========================================
# Reinstated as part of Task A7 to establish guardrails on parser and UI code growth.
# These thresholds block merges when complexity limits are exceeded.
#
# Enforcement:
# - Local: .githooks/pre-push runs `swiftlint lint --strict`
# - CI: .github/workflows/swiftlint.yml runs on all Swift code
# - Artifacts: SwiftLint reports are published to PRs for detailed analysis
#
# Thresholds tuned to allow 95%+ of existing code to pass while preventing
# future complexity regressions. Adjust thresholds when parser generators expand
# or design system refactoring requires higher limits.
#
# @todo #A7 Enable strict mode for main project after refactoring large files
#   CI currently runs main project (Sources/, Tests/) in informational mode because
#   3 files exceed type_body_length threshold: JSONParseTreeExporter.swift (2127 lines),
#   BoxValidator.swift (1738 lines), DocumentSessionController.swift (1634 lines).
#   After refactoring these files below 1500 lines, switch CI to --strict mode.
#
# Related tasks: A2 (CI pipeline), A8 (test coverage gates), A10 (duplication detection)
# ========================================

cyclomatic_complexity:
  warning: 30  # Functions with complexity > 30 trigger warnings
  error: 55    # Functions with complexity > 55 fail the build

function_body_length:
  warning: 250  # Functions > 250 lines trigger warnings
  error: 350    # Functions > 350 lines fail the build

type_body_length:
  warning: 1200  # Types > 1200 lines trigger warnings
  error: 1500    # Types > 1500 lines fail the build

nesting:
  type_level:
    warning: 5  # Nesting depth > 5 triggers warnings
    error: 7    # Nesting depth > 7 fails the build

excluded:
  - .build
  - .git
  - DOCS
  - FoundationUI

identifier_name:
  excluded:
    - id
