disabled_rules:
  - line_length
  - todo
  - type_name
  - identifier_name
  - force_try
  - file_length
  - function_parameter_count
  - redundant_string_enum_value
  - unneeded_synthesized_initializer
  - multiple_closures_with_trailing_closure
  - trailing_comma
  - opening_brace
  - closure_parameter_position
  - optional_data_string_conversion
  - vertical_whitespace

# ========================================
# Complexity Thresholds (Task A7)
# ========================================
# Reinstated as part of Task A7 to establish guardrails on parser and UI code growth.
# These thresholds block merges when complexity limits are exceeded.
#
# Enforcement:
# - Local: .githooks/pre-commit and .githooks/pre-push both run `swiftlint lint --strict`
# - CI: .github/workflows/swiftlint.yml runs on all Swift code (Sources, Tests, FoundationUI, CLI, samples)
# - Artifacts: SwiftLint reports are published to PRs for detailed analysis
#
# Thresholds tuned to the limits defined in DOCS/INPROGRESS/A7_SwiftLint_Complexity_Thresholds.md.
# Adjust thresholds only after coordinating via the automation workplan and documenting
# rationale inline so downstream tasks (A8, A10) stay aligned.
#
# @todo #A7 Refactor the remaining oversized types (JSONParseTreeExporter.swift,
#   BoxValidator.swift, DocumentSessionController.swift) so the local suppressions can
#   be removed while keeping type bodies under 200 lines each.
#
# Related tasks: A2 (CI pipeline), A8 (test coverage gates), A10 (duplication detection)
# ========================================

cyclomatic_complexity:
  warning: 8   # Encourage refactors before complexity hits the hard limit
  error: 10   # Functions with complexity > 10 fail the build

function_body_length:
  warning: 35  # Surface large bodies before they exceed the 40 line max
  error: 40   # Functions > 40 lines fail the build

type_body_length:
  warning: 180  # Highlight oversized types before hitting the 200 line max
  error: 200   # Types > 200 lines fail the build

nesting:
  type_level:
    warning: 4  # Prevent deeply nested control flow before the hard limit
    error: 5    # Nesting depth > 5 fails the build

excluded:
  - .build
  - .git
  - DOCS
  - FoundationUI
