disabled_rules:
  - line_length
  - todo
  - type_name
  - identifier_name
  - force_try
  - function_body_length
  - file_length
  - type_body_length
  - nesting
  - function_parameter_count
  - cyclomatic_complexity
  - redundant_string_enum_value
  - unneeded_synthesized_initializer
  - multiple_closures_with_trailing_closure
  - trailing_comma

excluded:
  - .build
  - .git
  - DOCS
  - FoundationUI

identifier_name:
  excluded:
    - id
