# FoundationUI SwiftLint Configuration
# Strict code quality enforcement for FoundationUI package
# Last Updated: 2025-11-07

# Rules to disable (keep minimal, only disable when absolutely necessary)
disabled_rules:
  - line_length  # Allow longer lines for SwiftUI view builders and complex expressions
  - todo  # Allow @todo markers for puzzle-driven development
  - force_try  # Occasionally necessary for test fixtures

# Excluded paths (tests may have different standards)
excluded:
  - .build
  - .git
  - .swiftpm
  - .tuist
  - DerivedData
  - Tests

# Enabled strict rules for FoundationUI
enabled_rules:
  - trailing_whitespace
  - trailing_newline
  - vertical_whitespace
  - statement_position
  - indentation_width
  - cyclomatic_complexity
  - control_statement
  - empty_enum_arguments
  - leading_whitespace
  - legacy_cggeom_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - mark_handler
  - multiple_closures_with_trailing_closure
  - operator_whitespace
  - sorted_imports
  - redundant_optional_initialization
  - redundant_string_enum_value
  - empty_count
  - no_space_in_method_call
  - unneeded_synthesized_initializer
  - redundant_discardable_let
  - implicit_return

# Rule configuration
naming:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - x
    - y
    - z
    - db

identifier_name:
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length: 2
  max_length: 50

function_body_length:
  warning: 80
  error: 150

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 600
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 2
  function_level: 3

function_parameter_count:
  warning: 7
  error: 10

# Mark handler for better code organization
mark_handler:
  severity: warning

# Allow some warnings in debug mode
default_severity: warning
