# SwiftLint Configuration for FoundationUI
# Zero tolerance for magic numbers, strict mode enabled

# Disable rules that conflict with formatters or are not applicable
disabled_rules:
  - trailing_whitespace # Handled by formatter

# Opt-in rules for enhanced code quality
opt_in_rules:
  - explicit_init
  - explicit_type_interface
  - no_magic_numbers
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_acl
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Exclude directories from linting
excluded:
  - Tests
  - .build
  - Package.swift
  - .swiftpm
  - DerivedData

# Line length configuration
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: false
  ignores_comments: false
  ignores_urls: true

# File length configuration
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Type body length configuration
type_body_length:
  warning: 300
  error: 500

# Function body length configuration
function_body_length:
  warning: 50
  error: 100

# Identifier name configuration
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - x
    - y
    - ds # Design System abbreviation
    - DS # Design System namespace

# Type name configuration
type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - DS # Design System namespace

# Custom rules for FoundationUI
custom_rules:
  # Ensure DS token usage instead of magic numbers
  design_system_token_usage:
    name: "Design System Token Usage"
    regex: '(?<!DS\.)(?<!\w)(8|12|16|24|10|999|6|0\.15|0\.25)(?!\w)'
    message: "Use Design System tokens (DS.*) instead of magic numbers"
    severity: warning

  # Ensure proper DocC documentation
  public_documentation:
    name: "Public API Documentation"
    regex: '^public (?!extension)'
    message: "Public declarations should have DocC documentation (///)"
    severity: warning

# Analyzer rules (require full compilation)
analyzer_rules:
  - unused_declaration
  - unused_import
