# FoundationUI SwiftLint Configuration
# Strict code quality enforcement for FoundationUI package
# Last Updated: 2025-11-16
# SwiftLint Version: 0.62.2

# Rules to disable (keep minimal, only disable when absolutely necessary)
disabled_rules:
  # Formatting is handled by swift-format
  - opening_brace
  - closure_parameter_position
  - trailing_comma
  - indentation_width
  - vertical_whitespace
  - vertical_parameter_alignment
  - function_body_length
  - cyclomatic_complexity

  # Non-formatting relaxations
  - line_length  # Allow longer lines for SwiftUI view builders and complex expressions
  - todo  # Allow @todo markers for puzzle-driven development
  - force_try  # Occasionally necessary for test fixtures
  - blanket_disable_command  # Allow file-level disables with @todo markers for future fixes
  - orphaned_doc_comment  # Conflicts with swiftlint:disable pragmas

# Excluded paths (tests may have different standards)
excluded:
  - .build
  - .git
  - .swiftpm
  - .tuist
  - DerivedData
  - Tests

# Opt-in rules (renamed from enabled_rules in SwiftLint 0.62+)
opt_in_rules:
  - trailing_whitespace
  - trailing_newline
  - statement_position
  - cyclomatic_complexity
  - control_statement
  - empty_enum_arguments
  - leading_whitespace
  - legacy_constant
  - legacy_constructor
  - multiple_closures_with_trailing_closure
  - function_name_whitespace  # Renamed from operator_whitespace
  - sorted_imports
  - implicit_optional_initialization  # Renamed from redundant_optional_initialization
  - redundant_string_enum_value
  - empty_count
  - no_space_in_method_call
  - unneeded_synthesized_initializer
  - redundant_discardable_let
  - implicit_return

# Rule configuration

identifier_name:
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - r
    - g
    - b
    - s1
    - s2
    - up
    - xxs
    - xs
    - s
    - m
    - l
    - xl

type_name:
  min_length: 2
  max_length: 50

function_body_length:
  warning: 80
  error: 150

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 5000
  error: 10000

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 2
  function_level: 3

function_parameter_count:
  warning: 7
  error: 10
