name: FoundationUI CI

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - "**"
    paths:
      - 'FoundationUI/**/*.swift'
      - 'FoundationUI/**/Package.swift'
      - 'FoundationUI/**/Package.resolved'
      - '.github/workflows/foundationui.yml'
  push:
    branches:
      - main
    paths:
      - 'FoundationUI/**/*.swift'
      - 'FoundationUI/**/Package.swift'
      - 'FoundationUI/**/Package.resolved'
      - '.github/workflows/foundationui.yml'

jobs:
  test-foundationui:
    name: Build and Test FoundationUI
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0"

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Show Swift version
        run: swift --version

      - name: Cache SwiftPM build artifacts
        uses: actions/cache@v4
        with:
          path: FoundationUI/.build
          key: ${{ runner.os }}-spm-foundationui-${{ hashFiles('FoundationUI/Package.swift', 'FoundationUI/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-foundationui-

      - name: Build FoundationUI framework
        run: |
          set -eo pipefail
          echo "Building FoundationUI framework..."
          cd FoundationUI
          swift build --target FoundationUI

      - name: Run FoundationUI tests
        run: |
          set -eo pipefail
          echo "Running FoundationUI tests..."
          cd FoundationUI
          swift test --filter FoundationUITests
