name: macOS Build

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - "**"
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - 'scripts/**'
      - 'Package.swift'
      - 'Package.resolved'
      - 'Project.swift'
      - 'Workspace.swift'
      - 'ISOInspector.xcodeproj/**'
      - 'ISOInspector.xcworkspace/**'
      - '.github/workflows/*.yml'
  push:
    branches:
      - main
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - 'scripts/**'
      - 'Package.swift'
      - 'Package.resolved'
      - 'Project.swift'
      - 'Workspace.swift'
      - 'ISOInspector.xcodeproj/**'
      - 'ISOInspector.xcworkspace/**'
      - '.github/workflows/*.yml'

jobs:
  macos-builds:
    name: macOS Archive & CLI Binary
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Tuist CLI release
        id: tuist-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          TOKEN="${GITHUB_TOKEN:-}"
          AUTH_HEADER=""
          if [ -n "${TOKEN}" ]; then
            AUTH_HEADER="Authorization: Bearer ${TOKEN}"
            export AUTH_HEADER
          fi
          python3 .github/scripts/get-tuist-version.py

      - name: Cache Tuist binary
        id: cache-tuist
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/tuist/${{ steps.tuist-version.outputs.tuist_version }}
          key: ${{ runner.os }}-tuist-${{ steps.tuist-version.outputs.tuist_version }}

      - name: Install Tuist
        env:
          TUIST_VERSION: ${{ steps.tuist-version.outputs.tuist_version }}
        run: |
          set -euo pipefail
          INSTALL_DIR="${RUNNER_TEMP}/tuist/${TUIST_VERSION}"
          mkdir -p "${INSTALL_DIR}"
          if [ ! -x "${INSTALL_DIR}/tuist" ]; then
            echo "Downloading Tuist ${TUIST_VERSION}"
            tmpdir=$(mktemp -d)
            curl -fL -o "${tmpdir}/tuist.zip" "https://github.com/tuist/tuist/releases/download/${TUIST_VERSION}/tuist.zip"
            unzip -q "${tmpdir}/tuist.zip" -d "${tmpdir}"
            rsync -a "${tmpdir}/" "${INSTALL_DIR}/"
            chmod +x "${INSTALL_DIR}/tuist"
            rm -rf "${tmpdir}"
          fi
          echo "${INSTALL_DIR}" >> "$GITHUB_PATH"

      - name: Show Tuist version
        run: tuist version

      - name: Select Xcode 16.0 (required for `.icon` assets)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0"

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Validate Tuist project definition
        run: tuist dump project > /dev/null

      - name: Install Tuist dependencies
        run: tuist install

      - name: Generate Xcode project with Tuist
        run: tuist generate --no-open

      - name: Run ISOInspectorAppTests
        run: swift test --filter ISOInspectorAppTests/

      - name: Archive ISOInspectorApp (unsigned)
        run: |
          set -eo pipefail
          xcodebuild archive \
            -workspace ISOInspector.xcworkspace \
            -scheme ISOInspectorApp-macOS \
            -destination 'generic/platform=macOS' \
            -archivePath build/ISOInspectorApp \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO

      - name: Build ISOInspectorCLI release binary
        run: swift build --product isoinspect --configuration release

      - name: Prepare artifacts
        run: |
          set -eo pipefail
          mkdir -p artifacts
          cp -R build/ISOInspectorApp.xcarchive artifacts/
          cli_path=$(swift build --product isoinspect --configuration release --show-bin-path)
          cp "$cli_path/isoinspect" artifacts/isoinspect

      - name: Upload ISOInspectorApp archive
        uses: actions/upload-artifact@v4
        with:
          name: ISOInspectorApp-unsigned-archive
          path: artifacts/ISOInspectorApp.xcarchive

      - name: Upload isoinspect binary
        uses: actions/upload-artifact@v4
        with:
          name: isoinspect-macos-release
          path: artifacts/isoinspect
