name: Swift (Linux)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-build-test:
    name: SwiftLint, Build, Test & Coverage (Linux)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Swift 5.9.2
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: '5.9.2'

      - name: SwiftLint
        uses: docker://ghcr.io/realm/swiftlint:0.53.0
        with:
          args: lint --strict

      - name: Cache SwiftPM build artifacts
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.swift', 'Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build (debug with tests)
        run: swift build --build-tests

      - name: Test with coverage
        run: swift test --enable-code-coverage

      - name: Coverage summary
        run: |
          set -eo pipefail
          profile=".build/debug/codecov/default.profdata"
          if [ ! -f "$profile" ]; then
            echo "::error::Coverage profile not found at $profile"
            exit 1
          fi
          binaries=$(find .build/debug -type f -name '*.xctest')
          if [ -z "$binaries" ]; then
            echo "::error::No test binaries found for coverage reporting"
            exit 1
          fi
          llvm-cov report --ignore-filename-regex='Tests/' --instr-profile="$profile" $binaries
